name: kubernetes validation
on:
  push:
    branches:
      - main

jobs:
  #kubeval-1:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: validate manifests in app
  #      uses: makocchi-git/actions-k8s-manifests-validate-kubeval@1.0.0
  #      with:
  #        files: app/*.yml
  kubeval-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: instrumenta/kubeval-action@master
        with:
          files: './app/*.yml'
    
  kube-score:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: kube-score check
      uses: piraces/kube-score-ga@v0.1.1
      with:
        manifests-folders: './app/*.yml'
        ignore-exit-code: true
  #conftest:
